# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# Fabric API
fabric_version=0.104.0+1.21.1

# Mod Properties
	mod_version = 1.21.1-0.2
	maven_group = com.blocklegend001
	archives_base_name = ReinforcedObsidian
jei_version=19.17.0.192
rei_version=16.0.762