# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.5

# Fabric API
fabric_version=0.102.0+1.21

# Mod Properties
	mod_version = 1.21-0.2
	maven_group = com.blocklegend001
	archives_base_name = ReinforcedObsidian
jei_version=19.8.2.99
rei_version=16.0.744