## Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.15-beta

## Mod Properties
mod_id=reinforcedobsidian
mod_name=ReinforcedObsidian
mod_license=All Rights Reserved
mod_version=26.1.1-0.1
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=Adds a block called reinforced obsidian, indestructibile by the wither and any type of explosion
